[package]
name = "crazyflie_server_rs"
version = "0.5.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread", "time"] }
rclrs = "0.6"
crazyflie-link = "0.3.0"
crazyflie-lib = "0.3.0"
crazyflie_interfaces = "*"
